body:
  - type: markdown
    attributes:
      value: |
        Thanks for wanting to improve zshclock!
        Fill out this form to submit a feature request!
  - type: textarea
    id: feature
    attributes:
      label: "What would you like to see zshclock add, change, remove, or improve?"
      placeholder: |
        Add bees. Add lots of bees. This clock doesn't have enough bees, and let me tell you, I freakin' LOVE bees, man.
      validations:
        required: true
  - type: textarea
    id: benefit
    attributes:
      label: "How would zshclock and/or its users benefit from this suggestion?"
      placeholder: |
        Bees are, like, really good for the environment? If zshclock had bees, it would definitely be more awesome. Plus, the clock could finally pollinate itself.
    validations:
      required: true
  - type: textarea
    id: additionals
    attributes:
      label: "Is there anything else you'd like to add to this feature request? Context, history, examples, etc."
      placeholder: |
        The bee was invented forever ago, and is standardized in most countries. There's over a bajillion different kinds.

        I'm not particular what kind of bee zshclock adds. Any kind would do, so long as there's lots of them. Please. And thank you.
  - type: checkboxes
    attributes:
      label: "Almost done! Check the box and hit the button to submit your request!"
      options:
        - label: "I understand this form is a request, and that there's no guarantee this feature will be added."
          required: true
